#!/bin/bash
set -xe
HOOK_TYPE_P="$1"
cd /
export CHROOT=1
. ./strapfuncs.sh
export R="/"

step $HOOK_TYPE_P

if [ "$HOOK_TYPE_P" = "extra" ]; then
	gpg --homedir "$R/home/user" --receive-keys 1EB2638FF56C0C53
	pushd extra_packages/sources
	    for pkg in cower pacaur ; do
            (cd $pkg && makepkg -sf && $SUDO pacman --noconfirm -r $R -U *.pkg.*)
	    done
	popd
else
    _hook_t=$(ls -1d ".installed_hooks/$HOOK_TYPE_P/"*.sh | wc -l)
    _hook_c=0
	for n in .installed_hooks/$HOOK_TYPE_P/*.sh; do
        _hook_c=$(( $_hook_c + 1 ))
        step "$1 hook [ $(( 100 * $_hook_c / $_hook_t ))% ] $_hook_c/$_hook_t :: $(basename $n)"
        . "$n"
	done
fi
